const products = [
  {
    id: 1,
    name: "Reusable Bamboo Straws",
    image: '/imgs/pexels-vie-studio-8148587.jpg',
    price: 9.99,
    description:
      "Replace single-use plastic straws with these eco-friendly bamboo straws. Each pack contains 4 straws.",
    stock: 50,
  },
  {
    id: 2,
    name: "Organic Cotton Tote Bag",
    image: '/imgs/ORG-12oz-tote-bag.webp',
    price: 14.99,
    description:
      "Durable and eco-friendly tote bag made from 100% organic cotton. Made with love and care. Dimensions: 15 x 16 inches.",
    stock: 30,
  },
  {
    id: 3,
    name: "Stainless Steel Water Bottle",
    image: '/imgs/images.jpg',
    price: 19.99,
    description:
      "Keep your drinks cold or hot with this insulated stainless steel water bottle. BPA-free and eco-friendly. Capacity: 20 oz.",
    stock: 20,
  },
  {
    id: 4,
    name: "Bamboo Toothbrush",
    image: '/imgs/pexels-pavel-danilyuk-7055299.jpg',
    price: 3.99,
    description:
      "Eco-friendly toothbrush made from sustainably sourced bamboo. Bristles are made from nylon-6 and can be recycled. Pack of 4.",
    stock: 100,
  },
  {
    id: 5,
    name: "Beeswax Food Wraps",
    image: '/imgs/GUEST_32be0197-7945-42ac-a21f-a63df809ae05.jpg',
    price: 12.99,
    description:
      "Reusable beeswax wraps to keep your food fresh without plastic. Set of 3 wraps in various sizes. Made with organic cotton and beeswax.",
    stock: 40,
  },
  {
    id: 6,
    name: "Compostable Trash Bags",
    image: '/imgs/stout-garbage-bags-stog3340e11-64_600.avif',
    price: 8.99,
    description:
      "Eco-friendly trash bags that are compostable and biodegradable. Pack of 50 bags. Capacity: 13 gallons. Dimensions: 24 x 30 inches.",
    stock: 60,
  },
  {
    id: 7,
    name: "Eco-friendly Laundry Detergent",
    image: '/imgs/31ftssij8ul-sl500-64380afd0caf3.webp',
    price: 15.99,
    description: "Biodegradable laundry detergent with natural ingredients.",
    stock: 25,
  },
  {
    id: 8,
    name: "Reusable Produce Bags",
    image: '/imgs/Mesh+Filled+5+Sizes.jpg',
    price: 10.99,
    description: "Set of 5 reusable mesh bags for fruits and vegetables.",
    stock: 80,
  },
  {
    id: 9,
    name: "Solar Powered Charger",
    image: '/imgs/SOLPOWBEN-30000mAh-Solar-Charger-Cell-Phone-iPhone-Portable-Power-Bank-Dual-5V-USB-Ports-2-Led-Light-Flashlight-Compass-Battery-Pack-Outdoor-Camping_f98cf7a7-fe10-45cc-9090-f.webp',
    price: 29.99,
    description: "Portable solar charger for your electronic devices.",
    stock: 10,
  },
  {
    id: 10,
    name: "Eco-friendly Notebook",
    image: '/imgs/imprinted-recycled-earth-friendly-notebook-jotters-ej2.webp',
    price: 6.99,
    description: "Notebook made from recycled paper.",
    stock: 70,
  },
  {
    id: 11,
    name: "Organic Cotton Face Mask",
    image: '/imgs/Kaarem_Mask_03w.webp',
    price: 5.99,
    description: "Reusable face mask made from organic cotton.",
    stock: 200,
  },
  {
    id: 12,
    name: "Bamboo Sunglasses",
    image: '/imgs/00024291529521_ALNO_9af49d98-0ef8-4343-be75-ad9da07991e5_1200x1200.webp',
    price: 24.99,
    description: "Stylish sunglasses with frames made from bamboo.",
    stock: 15,
  },
  {
    id: 13,
    name: "Eco-friendly Coffee Cup",
    image: '/imgs/BGC-612-tile-1_1024x1024@2x.webp',
    price: 13.99,
    description: "Reusable coffee cup made from sustainable materials.",
    stock: 35,
  },
  {
    id: 14,
    name: "Recycled Plastic Rug",
    image: '/imgs/orange-white-playa-rug-outdoor-rugs-vnc-o-w-8x10-64_600.avif',
    price: 49.99,
    description: "Durable outdoor rug made from recycled plastic bottles.",
    stock: 5,
  },
  {
    id: 15,
    name: "Plant-based Shampoo Bar",
    image: '/imgs/shampoo.jpg',
    price: 7.99,
    description: "Shampoo bar made from natural, plant-based ingredients.",
    stock: 90,
  },
];

module.exports = products;
